config/routes.rb
Aea2::Application.routes.draw do

  get "pages/livechat"
  match "livechat" => "pages#livechat" 

  resources :categories
  
  match 'assets/select_category'
  match 'assets/show_images'
  match 'assets/show_logos'
  match 'images' => 'assets#show_news_release_images'
  match 'story_images' => 'assets#show_news_release_images'
  match 'assets/show_news_release_images'
  match 'assets/show_news_archives'
  match 'assets/latest_news_release'
  resources :assets
  

   root :to => 'categories#index'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :category_id, :description, :name, :aea_file, :excerpt, 
                  :link_display_text, :link_url, :faq_question, :faq_answer, :asset_type, :short_title, :date_published
  attr_writer :current_step

  belongs_to :category
  mount_uploader :aea_file, AeaFileUploader

  validates_uniqueness_of :name

  extend FriendlyId
  friendly_id :name, use: :slugged

  def current_step
  	@current_step || steps.first
  end

  def steps
  	%w[select_category file_excerpt_desc]
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  http_basic_authenticate_with :name => ENV['HTTP_NAME'], :password => ENV['HTTP_PASS'], :only => [:new, :edit, :index]

  before_filter :load_latest_news, :except => :latest_news_release

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.find(:all, :include => :category, order: 'category_id asc')
    @categories = Category.all(order: 'name asc')
    @category = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end

  def latest_news_release
    category_pr = Category.find_by_slug("news-releases")
    @assets = Asset.find_all_by_category_id(category_pr.id, order: 'date_published desc')
    @latest_news = @assets.first
    @categories = Category.all(order: 'created_at desc')
  end

  def show_images
    @assets_images = Asset.find_all_by_asset_type('images')
    @categories = Category.all
  end

  def show_news_release_images
    @assets_news = Asset.find_all_by_asset_type('img-for-news-release')
  end

  def show_logos
    @assets_logos = Asset.find_all_by_asset_type('logos')
    @categories = Category.all 
  end

  def show_news_archives
    @categories = Category.all
    category_pr = Category.find_by_slug("news-releases")
    @assets = Asset.find_all_by_category_id(category_pr.id)
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])
    @categories = Category.all(order: 'created_at')
    @assets = Asset.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end

private

  def load_latest_news
    category_pr = Category.find_by_slug("news-releases")
    @ln_assets = Asset.find_all_by_category_id(category_pr.id, order: 'date_published desc')
    @latest_news = @ln_assets.first
  end

end

app/helpers/assets_helper.rb
module AssetsHelper

	def pr_category(category)
		if category.slug == 'news-releases'
			category.name
			pr = category.assets.last
			"<h5>#{pr.name}</h5>
			<small>#{pr.created_at.strftime('%B, %e %Y')}</small><br />
			#{pr.excerpt}<br /><br />
			#{link_to 'See press release', '/assets/' + pr.slug}<br />
			".html_safe


		end
	end

	def toggle_new_edit_links
		if action_name == 'new'
  		  "<p>#{link_to 'Back', assets_path}</p>".html_safe
		elsif action_name == 'edit'
		  "<p>#{link_to 'Show', @asset} |
		  		   #{link_to 'Back', assets_path}</p>".html_safe
		end
	end

end

app/views/assets/_faq_step.html.erb
<!-- FAQs -->
  <div class="field">
    <%= f.label :faq_question %><br />
    <%= f.text_area :faq_question, rows: '2', class: 'span6' %>
  </div>
  <div class="field">
    <%= f.label :faq_answer %><br />
    <%= f.text_area :faq_answer, rows: '3', class: 'span6' %>
  </div>
<!-- END FAQS -->

app/views/assets/_file_excerpt_desc_step.html.erb
  <div class="field">
    <%= f.label 'Upload' %><br /><%= f.file_field :aea_file %>
  </div>

  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_area :excerpt, class: 'span6', rows: '10' %>
  </div>


  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'span6', rows: '15' %>
  </div>

app/views/assets/_form.html.erb
<div class="show_content">
<%= tinymce %>
<h1>Assets<%= ': ' + action_name.capitalize %></h1>
<%= toggle_new_edit_links %>

<%= form_for(@asset, :html => {:multipart => true}) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#= render "#{@asset.current_step}_step", :f => f %>

  <div class="field">
    <label><%#= f.label :name %>Title (Full or long Title)</label><br />
    <%= f.text_field :name, class: 'span6' %>
  </div>

  <div class="field">
    <%= f.label :short_title %><br />
    <%= f.text_field :short_title, class: 'span6' %>
  </div>

  <div class="field dateselect">
    <%= f.label :date_published %><br />
    <%#= select_date Date.today, :prefix => :date_published %><br />
    <%= date_select :asset, :date_published %>
  </div>

  <div class="field">
    <label>Asset Type</label>
    <label class="radio">
      <%= f.radio_button(:asset_type, "links") %>
      Link
    </label>
    <label class="radio">
      <%= f.radio_button(:asset_type, "img-for-news-release") %>
      Image for Press Releases
    </label>
    <label class="radio">
      <%= f.radio_button(:asset_type, "images") %>
      Image
    </label>
    <label class="radio">
      <%= f.radio_button(:asset_type, "logos") %>
      Logo
    </label>
    <label class="radio">
      <%= f.radio_button(:asset_type, "faq-question") %>
      FAQ Question
    </label>
    <label class="radio">
      <%= f.radio_button(:asset_type, "none") %>
      None
    </label>
  </div><br />

  <div class="field">
    <%= f.label :category_id %><br /><%= f.select(:category_id, Category.order("name").map { |c| [c.name, c.id] } ) %><br />
 </div>

   <div class="field">
    <%= f.label 'Upload' %><br /><%= f.file_field :aea_file %>
  </div>

<a href="#press-release-section" data-toggle="collapse" data-target="#press-release-section" class="btn btn-block" style="margin-bottom:1em;">Show Press Release Fields</a>
<div id="press-release-section" class="collapse">
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_area :excerpt, class: 'span6 tinymce', rows: '10' %>
  </div>


  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'span6 tinymce', rows: '15' %>
  </div>
</div>

  <!-- FAQs -->
<a href="#faq-section" data-toggle="collapse" data-target="#faq-section" class="btn btn-block" style="margin-bottom:1em;">Show FAQ section</a>
<div id="faq-section" class="collapse">
  <div class="field">
    <%= f.label :faq_question %><br />
    <%= f.text_area :faq_question, rows: '2', class: 'span6 tinymce' %>
  </div>
  <div class="field">
    <%= f.label :faq_answer %><br />
    <%= f.text_area :faq_answer, rows: '3', class: 'span6 tinymce' %>
  </div>
</div>
<!-- END FAQS -->

<!-- URLs -->
<a href="#url-section" data-toggle="collapse" data-target="#url-section" class="btn btn-block" style="margin-bottom:1em;">Show Link Section</a>
<div id="url-section" class="collapse">
  <div class="field">
    <%= f.label :link_display_text %><br />
    <%= f.text_field :link_display_text, class: 'span6' %>
  </div>
  <div class="field">
    <%= f.label :link_url %><br />
    <%= f.text_field :link_url, class: 'span6' %>
  </div>
</div>
<!-- END URLs -->








  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/assets/_link_url_step.html.erb
<!-- URLs -->
  <div class="field">
    <%= f.label :link_display_text %><br />
    <%= f.text_field :link_display_text, class: 'span6' %>
  </div>
  <div class="field">
    <%= f.label :link_url %><br />
    <%= f.text_field :link_url, class: 'span6' %>
  </div>
<!-- END URLs -->

app/views/assets/_select_category_step.html.erb
 <div class="field">
    <%= f.label :category_id %><br /><%= f.select(:category_id, Category.order("name").map { |c| [c.name, c.id] } ) %><br />
 </div>

app/views/assets/edit.html.erb
<%= render 'form' %>

app/views/assets/index.html.erb
<div class="row-fluid span6 show_content" style="">
  <h1 class="pull-left">Assets</h1>
  <%= button_to  'Add new asset', new_asset_path, class: 'pull-right btn btn-primary', method: 'get' %>
<table width="575" class="table table-striped">
  <tr>
    <th>Asset</th>
    <th>Category</th>
    <th>&nbsp;</th>

  </tr>
<% @assets.each do |asset| %>
  <tr>
    <td width="300"><%= link_to asset.name, asset.aea_file_url, target: '_blank' %> </td>
    <td width="130" valign="top"><% @category.each do |cat| %>
        <% if cat.id == asset.category_id %>
          <%= link_to cat.name, cat %>
          
        <% end %>
      <% end %> </td>
      <td width="60">
        <%= link_to '<i class="icon-eye-open"></i>'.html_safe, asset %>
        <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_asset_path(asset) %>
    <%= link_to '<i class="icon-trash"></i>'.html_safe, asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

</div>

app/views/assets/latest_news_release.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="span7">
	<div class="row-fluid">
		<div class="span11 offset1">
			<div class="span8">
				<h3>Latest News Release</h3>
				<h1><%= @latest_news.name %></h1>
				<%= @latest_news.description.html_safe %><br />
				<%#= image_tag @latest_news.aea_file_url(:medium) %>
				<%= link_to 'Download PDF', @latest_news.aea_file_url, target: '_blank' %>
				 
</div>
<div class="span4">
	<h3 style="padding-top:73px;">News Release Archive</h3>
	<ul id="assets" class="topMargin" style="float:left;padding-top:0;margin-left:12px;">
		<% @assets.each do |a| %>
			<li style="width:100%;"><%= link_to a.short_title, a.aea_file_url, target: '_blank' %></li>
		<% end %>
	</ul>
</div>
</div>
</div>
</div>
</div>

<% @categories.each do |category| %>
  <% content_for :sb_box do %>
          <%= pr_category(category) %>
  <% end %>
<% end %>

app/views/assets/new.html.erb
<%= render 'form' %>

app/views/assets/select_category.html.erb
<%= form_for(@asset, :html => {:multipart => true}) do |f| %>
	
	<div class="field">
    <%= f.label :category_id %><br /><%= f.select(:category_id, Category.order("name").map { |c| [c.name, c.id] } ) %><br />
  </div>

	<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span7">
    <div class="row-fluid">
      <div class="offset1 span11">
        <div class="span8">
          <h1><%= @asset.name %></h1>
          
          <%= @asset.description.html_safe %>
          <br />
          <% if @asset.aea_file? %>
            <%= image_tag @asset.aea_file_url(:medium) %><br />
            <%= link_to 'Download', @asset.aea_file_url %>
          <% end %>
                <p><%= link_to 'Edit', edit_asset_path(@asset) %> |
                <%= link_to 'Back', assets_path %></p>
</p>

        </div>
        <div class="span3">
          <!--
          <ul id="assets" style="padding-top:72px;">
          <%# @pr_assets.each do |pr| %>
            <li><%#= link_to pr.short_title, pr.aea_file_url, target: '_blank' %></li>
          <%# end %> -->
        </ul>
        </div>

      </div>

    </div>


  </div>
</div>















<% @categories.each do |category| %>
  <% content_for :sb_box do %>
          <%= pr_category(category) %>
  <% end %>
<% end %>

app/views/assets/show_images.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="span7">
	<div class="row-fluid">
		<div class="span11 offset1">
			<div class="span8">
				<h1>Images</h1>
				<p>These images are provided for editorial and promotional use by members of the American Electrology Association and the media. Please read <a href="https://aea2-assets.s3.amazonaws.com/uploads/AEA-BrandStandards-summer2012-v2.pdf" target="_blank">AEA Logo Usage Guidelines (pdf)</a> for acceptable use of these images. </p>
<% unless @assets_images.nil? %>
	<% @assets_images.each do |a| %>
		<div class="span5" style="display:block;text-align:center;border:1px solid #e2e2e2;margin:0 10px 10px 0;"><%= image_tag a.aea_file_url(:medium) %><br /><%= link_to a.name, a.aea_file_url %> </div>
	<% end %>
<% end %>
</div>
<div class="span4">
		<ul id="assets" class="topMargin">
	<li><a href="https://aea2-assets.s3.amazonaws.com/uploads/AEA-BrandStandards-summer2012-v2.pdf" target="_blank">AEA Logo Usage Guidelines (pdf)</a></li>
	</ul>
	</div>
</div>
</div>
</div>
</div>

<% @categories.each do |category| %>
  <% content_for :sb_box do %>
          <%= pr_category(category) %>
  <% end %>
<% end %>

 

app/views/assets/show_logos.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="span7">
			<div class="row-fluid">
				<div class="span11 offset1">
					<div class="span8">
						<h1>Logos</h1>
						<p>These logos are provided for use by members of the American Electrology Association and the media. Please read <a href="https://aea2-assets.s3.amazonaws.com/uploads/AEA-BrandStandards-summer2012-v2.pdf" target="_blank">AEA Logo Usage Guidelines (pdf)</a> for acceptable logo standards and practices.</p>

						<%= image_tag 'logo-wo-tagline.gif', class: 'logo-image' %>
						<h3>LOGO – without tagline</h3>
							<p>The logo shown above is the 2-color version, without tagline. Click on the links below to download individual logo files, or <a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_logo_pack.zip"  target="_blank">click here to download the AEA Logo Pack.</a> The pack contains all the logo file formats (with and without tagline) in one zipped folder.</p>

							<h5>EPS</h5>
							<ul class="logo-list">
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-color-2color.eps.zip" />AEA-logo-color-2color.eps.zip</a></li>
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-black.eps.zip" />AEA-logo-black.eps.zip</a></li>
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-white.eps.zip" />AEA-logo-white.eps.zip</a></li>
							</ul>

							<h5>JPG</h5>
							<ul class="logo-list">
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-color-2color.jpg" />AEA-logo-color-2color.jpg</a></li>
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-black.jpg" />AEA-logo-black.jpg</a></li>
							</ul>

							<h5>PNG</h5>
							<ul class="logo-list">
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-color-2color.png" />AEA-logo-color-2color.png</a></li> 
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-black.png" />AEA-logo-black.png</a></li>
								<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-white.png" />AEA-logo-white.png</a></li>
							</ul>

							<hr />

						<%= image_tag 'logo-w-tagline.gif', class: 'logo-image' %>
						<h3>LOGO – with tagline</h3>
						<p>The logo shown above is the black version, with tagline. Click on the links below to download individual logo files, or <a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_logo_pack.zip" target="_blank">click here to download the AEA Logo Pack.</a> The pack contains all the logo file formats (with and without tagline) in one zipped folder.</p>

						<h5>EPS</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-color-2color-tagline.eps.zip" />AEA-logo-color-2color-tagline.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-black-tagline.eps.zip" />AEA-logo-black-tagline.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-white-tagline.eps.zip" />AEA-logo-white-tagline.eps.zip</a></li>
						</ul>

						<h5>JPG</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-color-2color-tagline.jpg" />AEA-logo-color-2color-tagline.jpg</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-black-tagline.jpg" />AEA-logo-black-tagline.jpg</a></li>
						</ul>

						<h5>PNG</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-color-2color-tagline.png" />AEA-logo-color-2color-tagline.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-black-tagline.png" />AEA-logo-black-tagline.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-logo-white-tagline.png" />AEA-logo-white-tagline.png</a></li>
						</ul>

						<hr />

						<%= image_tag 'logo-tagline-only.gif', class: 'logo-image' %>
						<h3>TAGLINE only</h3>
						<p>The tagline shown above is the 70gray version. Click on the links below to download individual tagline files, or <a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_tagline_pack.zip" target="_blank">click here to download the AEA Tagline Pack.</a> The pack contains all the tagline file formats in one zipped folder.</p>

						<h5>EPS</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-70gray.eps.zip" />AEA-Tagline-70gray.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-black.eps.zip" />AEA-Tagline-black.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-white.eps.zip" />AEA-Tagline-white.eps.zip</a></li>
						</ul>

						<h5>JPG</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-70gray.jpg" />AEA-Tagline-70gray.jpg</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-black.jpg" />AEA-Tagline-black.jpg</a></li>
						</ul>

						<h5>PNG</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-70gray.png" />AEA-Tagline-70gray.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-black.png" />AEA-Tagline-black.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-Tagline-white.png" />AEA-Tagline-white.png</a></li>
						</ul>

						<hr />

						<%= image_tag 'logo-member-seal.gif', class: 'logo-image' %>
						<h3>MEMBER SEAL</h3>
						<p>The member seal shown above is the 2-color version. Click on the links below to download individual tagline files, or <a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_member_seal_pack.zip" target="_blank">click here to download the AEA Member Seal Pack.</a> The pack contains all the member seal file formats in one zipped folder..</p>

						<h5>EPS</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-2color.eps.zip" />AEA-memberseal-2color.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-black.eps.zip" />AEA-memberseal-black.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-white.eps.zip" />AEA-memberseal-white.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-2color-notext.eps.zip" />AEA-memberseal-2color-notext.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-black-notext.eps.zip" />AEA-memberseal-black-notext.eps.zip</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-white-notext.eps.zip" />AEA-memberseal-white-notext.eps.zip</a></li>
						</ul>

						<h5>JPG</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-2color.jpg" />AEA-memberseal-2color.jpg</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-black.jpg" />AEA-memberseal-black.jpg</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-2color-notext.jpg" />AEA-memberseal-2color-notext.jpg</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-black-notext.jpg" />AEA-memberseal-black-notext.jpg</a></li>
						</ul>

						<h5>PNG</h5>
						<ul class="logo-list">
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-2color.png" />AEA-memberseal-2color.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-black.png" />AEA-memberseal-black.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-white.png" />AEA-memberseal-white.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-2color-notext.png" />AEA-memberseal-2color-notext.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-black-notext.png" />AEA-memberseal-black-notext.png</a></li>
							<li><a href="https://s3.amazonaws.com/aea2-assets/logos/AEA-memberseal-white-notext.png" />AEA-memberseal-white-notext.png</a></li>
						</ul>


		</div>

				<div class="span4">
					<ul id="assets" class="topMargin" style="float:left;margin-left:12px;margin-top:-10px;" >
						<li style="width:100%;"><a href="https://aea2-assets.s3.amazonaws.com/uploads/AEA-BrandStandards-summer2012-v2.pdf" target="_blank">AEA Logo Usage Guidelines (pdf)</a></li>
						<li style="width:100%;"><a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_logo_pack.zip" target="_blank">AEA Logo Pack (zip)</a></li>
						<li style="width:100%;"><a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_member_seal_pack.zip" target="_blank">AEA Member Seal Pack (zip)</a></li>
						<li style="width:100%;"><a href="https://s3.amazonaws.com/aea2-assets/uploads/AEA_tagline_pack.zip" target="_blank">AEA Tagline Pack (zip)</a></li>
					</ul>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/assets/show_news_release_images.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="span7">

	<div class="row-fluid">

		<div class="span11 offset1">
			<div class="span8">
				<h1>Image Library for Electrolysis Stories</h1>
				<p>Download these high-resolution images for use with their respective <a href="/">electrolysis stories.</a></p>
<% unless @assets_news.nil? %>
	<% @assets_news.each do |a| %>
		<div class="span5" style="display:block;text-align:center;border:1px solid #e2e2e2;margin:0 10px 10px 0;"><%= image_tag a.aea_file_url(:medium) %><br /><%= link_to a.name, a.aea_file_url %> </div>
	<% end %>
<% end %>
</div>
<div class="span4">
		<ul id="assets" class="topMargin">
	<li><a href="https://aea2-assets.s3.amazonaws.com/uploads/AEA-BrandStandards-summer2012-v2.pdf" target="_blank">AEA Logo Usage Guidelines (pdf)</a></li>
	</ul>
	</div>
</div>
</div>
</div>
</div>