config/routes.rb
Aea2::Application.routes.draw do

  get "pages/livechat"
  match "livechat" => "pages#livechat" 

  resources :categories
  
  match 'assets/select_category'
  match 'assets/show_images'
  match 'assets/show_logos'
  match 'images' => 'assets#show_news_release_images'
  match 'story_images' => 'assets#show_news_release_images'
  match 'assets/show_news_release_images'
  match 'assets/show_news_archives'
  match 'assets/latest_news_release'
  resources :assets
  

   root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :layout, :slug, :excerpt
  has_many :assets

  validates_uniqueness_of :name

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  http_basic_authenticate_with :name => ENV['HTTP_NAME'], :password => ENV['HTTP_PASS'], :only => [:new, :edit]

  before_filter :load_latest_news

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all(order: 'created_at')
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @categories = Category.all(order: 'created_at')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

private

  def load_latest_news
    category_pr = Category.find_by_slug("news-releases")
    @ln_assets = Asset.find_all_by_category_id(category_pr.id, order: 'date_published desc')
    @latest_news = @ln_assets.first
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
	def assets_present(category)
		if category.layout == "float"
        	"span4 rightBorder"
        else
        	"span10"
        end
	end

	def category_type(category)
		if category.layout == "2col-1col" #about elec/aea - links to files
			html = ""
			html << "<div class=\"span8\">
          		#{category.excerpt.to_s.html_safe}
        	</div>
        	<div class=\"span4\">
	          	<ul id=\"assets\">"
	          		if category.assets.present?
	          		category.assets.each do |ca|
	          			html << "<li style=\"width:100%\">#{link_to ca.name, ca.aea_file_url, target: '_blank'}</li>"
	          		end
	          	end 
	         html << "</ul>
        	</div>"

		elsif category.layout == "1col-2col" #stories - links to files
			html = ""
			html << "<div class=\"span4\">
          		#{category.excerpt.to_s.html_safe}
        	</div>

        	<div class=\"span8\">"
        	html << "<div style=\"margin-left:30px;\"><ul id=\"assets\" style=\"margin-top:-11px;\">"
        		if category.assets.present?
        			category.assets.each do |ca|
        				if ca.asset_type != "img-for-news-release"
        				html << "<li width=\"100%\" class=\"question-links\">#{link_to ca.name, ca.aea_file_url, target: '_blank'}</li>"
        				end
        			end
        			html << "</ul></div>"
        		end
        	html << "</div>"

		elsif category.layout == "1col-2col-faq" #faqs - links to unhide answers
			html = ""
			html << "<div class=\"span4\">
          		#{category.excerpt.to_s.html_safe}
        	</div>
        	<div class=\"span8\">"
        	html << "<div style=\"margin-left:30px;\"><ul id=\"assets\" style=\"margin-top:-11px;\">"
        		if category.assets.present?
        			
        			category.assets.each do |ca|
        				if ca.asset_type == "faq-question"
        				html << "<li width=\"100%\" class=\"question-links\"><a href=\"##{'faq'+ca.id.to_s}\" data-toggle=\"collapse\" data-target=\"##{'faq'+ca.id.to_s}\">#{ca.faq_question}</a>"
        				html << "<div id=\"#{'faq'+ca.id.to_s}\" class=\"collapse c-width\" style=\"margin-bottom:0em;color:#008fc5;background-color:#e6f4f9;padding-left:4px;\">#{ca.faq_answer}</div></li>"
        				end
        			end
        			html << "</ul></div>"
        		end
        	html << "</div>"			

	    else category.layout == "1col-2col-resources" #resources - links to directories URLs
	    	html = ""
	    	html << "<div class=\"span4\">
          		#{category.excerpt.to_s.html_safe}
        	</div>
        	<div class=\"span8 float-right\">
	          	<ul id=\"assets\">"
	          	if category.assets.present?
	        		category.assets.each do |ca|
	        			if ca.asset_type == "links"
	        				if ca.link_display_text == "AEA Brand Guidelines (PDF)"
	        					html << "<li class=\"float-links\">#{link_to ca.link_display_text, ca.link_url, target: '_blank'}</li>"
	        				else
	        					html << "<li class=\"float-links\">#{link_to ca.link_display_text, ca.link_url }</li>"
	        				end
	        			end
	        		end
	        	end
	        
	        html << "</ul>
        	</div>"
	    end
	end


	def hide_pr(category)
		if category.slug == 'news-releases'
			"hidden"
		end
	end

	def divider(category)
		if category.slug == 'news-releases' || category.slug == 'resources'
			''
		else
			'<div style="border-top:1px solid #6d6e71;margin:7px 30px -7px 50px;"></div>'
		end
	end

	def pr_category(category)
		if @current_action != 'latest_news_release'
			if category.slug == 'news-releases'
				category.name
				pr = category.assets.first
				"<h5>#{pr.name}</h5>
				#{pr.excerpt}<br /><br />
				<ul id=\"assets\" style=\"margin-left:15px;\">
				<li style=\"width:100%;margin-left:0px;\">#{link_to 'News release archive', '/assets/latest_news_release', class: 'sb-release-link' }</li>
				</ul>
				<br />
				".html_safe
			end
		else
			""
		end
	end

end

app/views/categories/_form.html.erb
<div class="show_content">

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'span6' %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_area :excerpt, class: 'span6',  rows: '10' %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'span6',  rows: '10' %>
  </div>

 <div>
     <label class="radio">
       <%= f.radio_button(:layout, "2col-1col") %>
       About Elec./AEA - links to files
     </label>
 
     <label class="radio">
       <%= f.radio_button(:layout, "1col-2col") %>
       Stories - Links to files
     </label>

     <label class="radio">
       <%= f.radio_button(:layout, "1col-2col-faq") %>
       FAQs - Links to files
     </label>

     <label class="radio">
       <%= f.radio_button(:layout, "1col-2col-resources") %>
       Resources - Links to URLs
     </label>
 </div>

 <br/><br/>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/categories/_pr-sidebar.html.erb
<%= pr_category(category) %>

<!--
<p>Updated 3:26 PM ET, Friday, September 7, 2012</p>

<h5>Trend Report: From Barely There to Totally Bare, Hair Removal Goes All The Way This Season</h5>

<p><em>Getting smooth is easier than ever with a wide variety of options available.</em></p> 

<p>Before you tie on that teeny-weeny bikini this summer, you'll want to check out this summer's hottest trend in hair removal: barely there to totally bare. We're talking about body hair, and while everyone has it, this season, it's hot to not. So before hitting the beach, ladies are looking for ways to get smooth. There are a number of ways to get rid of unwanted hair—no matter  …</p>

<p>See full press release</p> -->

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<style>
/*dl {width:100px;border:1px solid red;float:left;width:50%;}
ul#assets li {list-style-image:url(/assets/li-arrow.png);}*/
ul#assets li {float:left;width:40%;}
.red1 {border-top:1px solid red;}
.black {border-top:1px solid black;}
</style>


<div class="row"><!-- right content main -->
  <div class="span7"><!-- inner container -->
  <% @categories.each do |category| %>
    <!-- h3 section title -->
    <div class="row-fluid <%= hide_pr(category) %>">
      <div class="span11 offset1">
        <h3><%= category.name %></h3>
      </div>
    </div>
    <!-- section body -->
    <div class="row-fluid <%= hide_pr(category) %>">
      <div class="span11 offset1">
        <%= category_type(category).html_safe %>
      </div>
    </div>
    <%= divider(category).html_safe %>
  <% end %>
  </div><!-- inner container END -->
</div><!-- right content main END -->


<!--

  <%#= link_to 'New Category', new_category_path %> | <%#= link_to 'New Asset', new_asset_path %> -->

<% @categories.each do |category| %>
  <% content_for :sb_box do %>
          <%= pr_category(category) %>
  <% end %>
<% end %>



</div>
<br />

app/views/categories/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<style>
/*dl {width:100px;border:1px solid red;float:left;width:50%;}
ul#assets li {list-style-image:url(/assets/li-arrow.png);}*/
ul#assets li {float:left;width:40%;}
</style>

<div class="row-fluid">
	<div class="row-fluid<%#= hide_pr(category) %>" style="margin:40px 50px 0 50px;">
		<div class=" span7">
			<h1><%= @category.name %></h1>
			<p><%= @category.description.html_safe %></p>

			<%= link_to 'Edit', edit_category_path(@category) %> |
			<%= link_to 'Back', categories_path %>
		</div>


		<div class="span3">	
			<ul id="assets" style="margin-top:10px;">
			  <% @category.assets.each do |ca| %>
			    <li style="width:100%;">
				    <%= link_to ca.name, ca.aea_file_url, target: '_blank' %>
				    <%#= ca.description.html_safe %>
			    </li>
			    <% end %>
			</ul>
		</div>
	</div>
</div>

<% @categories.each do |category| %>
  <% content_for :sb_box do %>
          <%= pr_category(category) %>
  <% end %>
<% end %>